export const seeds = [
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 36,
        "spacingInchesY": 12,
        "daysToHarvest": 89,
        "earliestPlantDate": "06/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Corn",
        "name": "Sweet",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "3e5d8a69-5ea8-4f77-8043-19970067f508"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 30,
        "spacingInchesY": 18,
        "daysToHarvest": 95,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Habanero",
        "inventory": 3,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "3f5e7210-ec8a-4574-a3f8-d1f6a7c9f474"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 6,
        "spacingInchesY": 6,
        "daysToHarvest": 50,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Vegetable",
        "subcategory": "Lettuce",
        "name": "Salad Bowl",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "30f8f7c9-174f-4a7c-abf0-be5572fecc2d"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 18,
        "spacingInchesY": 6,
        "daysToHarvest": 45,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Vegetable",
        "subcategory": "Lettuce",
        "name": "Black Seeded Simpson",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "0568b0f8a-6aa8-4108-8118-bfc7ba7a05cf"
    },
    {
        "minDaysToGerm": 14,
        "maxDaysToGerm": 21,
        "spacingInchesX": 18,
        "spacingInchesY": 24,
        "daysToHarvest": 75,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Flower",
        "subcategory": "Sunflower",
        "name": "Mammoth Russian",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "65906be1-5b2e-4bed-b47e-af989ddaf2df"
    },
    {
        "minDaysToGerm": 8,
        "maxDaysToGerm": 12,
        "spacingInchesX": 12,
        "spacingInchesY": 12,
        "daysToHarvest": 60,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Kale",
        "name": "Dwarf Blue Curled",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "204cacc5-ebca-4a3e-a562-e59b07547c2c"
    },
    {
        "minDaysToGerm": 6,
        "maxDaysToGerm": 8,
        "spacingInchesX": 60,
        "spacingInchesY": 72,
        "daysToHarvest": 78,
        "earliestPlantDate": "06/01",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Watermelon",
        "name": "Ultra Cool Hybrid",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "e078afef-7f83-4a9a-b64f-d6c82f439942"
    },
    {
        "minDaysToGerm": 21,
        "maxDaysToGerm": 28,
        "spacingInchesX": 10,
        "spacingInchesY": 10,
        "daysToHarvest": 75,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Herb",
        "subcategory": "Parsley",
        "name": "Italian Flat Leaf",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "7541e10f-7e15-4cc0-a095-dc0957e6c204"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 36,
        "spacingInchesY": 24,
        "daysToHarvest": 70,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Tomato",
        "name": "Large Red Cherry",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "3f50eb00-b25a-4c18-a67d-f08acbd1e7b5"
    },
    {
        "minDaysToGerm": 8,
        "maxDaysToGerm": 12,
        "spacingInchesX": 20,
        "spacingInchesY": 20,
        "daysToHarvest": 70,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Herb",
        "subcategory": "Catnip",
        "name": "Catnip",
        "inventory": 2,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "da623ff9-c22a-4e57-b9d9-36766f2a56f0"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 2,
        "spacingInchesY": 2,
        "daysToHarvest": 68,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pea",
        "name": "Green Arrow",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "227e9f3b-2299-4839-984b-d9c7206e97e3"
    },
    {
        "minDaysToGerm": 5,
        "maxDaysToGerm": 7,
        "spacingInchesX": 10,
        "spacingInchesY": 10,
        "daysToHarvest": 80,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Herb",
        "subcategory": "Basil",
        "name": "Lemon",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "8cf89746-733a-4f23-855f-c678283b540b"
    },
    {
        "minDaysToGerm": 8,
        "maxDaysToGerm": 14,
        "spacingInchesX": 12,
        "spacingInchesY": 12,
        "daysToHarvest": 85,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Herb",
        "subcategory": "Oregano",
        "name": "Vulgare",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "782fc213-b650-4d86-81a3-779f68bce525"
    },
    {
        "minDaysToGerm": 8,
        "maxDaysToGerm": 12,
        "spacingInchesX": 15,
        "spacingInchesY": 3,
        "daysToHarvest": 72,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Vegetable",
        "subcategory": "Carrot",
        "name": "Long Imperator",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "d2587e4a-3a37-4aa2-9831-6911af31723e"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 30,
        "spacingInchesY": 18,
        "daysToHarvest": 60,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Long Thin Cayenne",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "777c4ae9-79e2-416e-ab02-8c4884692a7d"
    },
    {
        "minDaysToGerm": 6,
        "maxDaysToGerm": 14,
        "spacingInchesX": 30,
        "spacingInchesY": 24,
        "daysToHarvest": 60,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Vegetable",
        "subcategory": "Pea",
        "name": "Sugar Daddy",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "4caac82e-0219-47b7-9d0c-27e447fd086b"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 30,
        "spacingInchesY": 18,
        "daysToHarvest": 73,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Serrano Chili",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "640d2094-7d1a-42cd-9767-c8124a5ee554"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 30,
        "spacingInchesY": 18,
        "daysToHarvest": 85,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Cascabella",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "cd7cefc8-e79b-4ab0-afcb-ae4b08fc625a"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 20,
        "spacingInchesX": 12,
        "spacingInchesY": 12,
        "daysToHarvest": 85,
        "earliestPlantDate": "06/01",
        "latestPlantDate": "07/31",
        "category": "Herb",
        "subcategory": "Rosemary",
        "name": "Rosemary",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "e1d5d6a1-a25c-47b8-ad5a-73bd2aa38742"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 24,
        "spacingInchesY": 1,
        "daysToHarvest": 75,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Hot Mix",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "fa16e852-faaa-49ea-8374-b46ba7427121"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 30,
        "spacingInchesY": 18,
        "daysToHarvest": 75,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Garden Leader Monster Bell",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "efac7f63-5762-4c06-9417-714a1dba128b"
    },
    {
        "minDaysToGerm": 10,
        "maxDaysToGerm": 12,
        "spacingInchesX": 30,
        "spacingInchesY": 18,
        "daysToHarvest": 70,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Bell Color Mix",
        "inventory": 1,
        "seedsInPacket": 100,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "92de2ba0-ca04-4f8c-9c9c-fc7280d68fc7"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 36,
        "spacingInchesY": 48,
        "daysToHarvest": 41,
        "earliestPlantDate": "05/24",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Squash",
        "name": "Summer Dixie Hybrid",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "ce06b66a-3c74-4b0f-a1b4-d3a91409ea02"
    },
    {
        "minDaysToGerm": 6,
        "maxDaysToGerm": 8,
        "spacingInchesX": 60,
        "spacingInchesY": 72,
        "daysToHarvest": 95,
        "earliestPlantDate": "06/01",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Watermelon",
        "name": "Crimson Sweet",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "df43d87a-f6ec-482f-b0c1-74e51e192bfe"
    },
    {
        "minDaysToGerm": 5,
        "maxDaysToGerm": 10,
        "spacingInchesX": 10,
        "spacingInchesY": 10,
        "daysToHarvest": 85,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Herb",
        "subcategory": "Basil",
        "name": "Genovese",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "2595bcb3-972a-4195-8e24-01e4ae683948"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 10,
        "spacingInchesY": 10,
        "daysToHarvest": 40,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Vegetable",
        "subcategory": "Mesclun",
        "name": "Gourmet Greens Mixture",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "c431a23d-edc7-4288-a0ef-81169e9b7167"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 36,
        "spacingInchesY": 24,
        "daysToHarvest": 65,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Tomato",
        "name": "Supersweet 100 VF Hybrid",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "82dcf0e9-7999-455d-a5cb-3db36cf30d1f"
    },
    {
        "minDaysToGerm": 2,
        "maxDaysToGerm": 3,
        "spacingInchesX": 1,
        "spacingInchesY": 1,
        "daysToHarvest": 7,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Microgreens",
        "name": "Rainbow Mix",
        "inventory": 1,
        "seedsInPacket": 23,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "05515ee36-7ca4-4c09-b00c-fcfaa0e64aa3"
    },
    {
        "minDaysToGerm": 12,
        "maxDaysToGerm": 15,
        "spacingInchesX": 8,
        "spacingInchesY": 8,
        "daysToHarvest": 90,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "04/30",
        "category": "Fruit",
        "subcategory": "Strawberry",
        "name": "Alpine",
        "inventory": 1,
        "seedsInPacket": 125,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "a8fbf0fa-2984-4fd0-a4db-9f5fd65323a1"
    },
    {
        "minDaysToGerm": 14,
        "maxDaysToGerm": 21,
        "spacingInchesX": 24,
        "spacingInchesY": 10,
        "daysToHarvest": 720,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "04/30",
        "category": "Vegetable",
        "subcategory": "Asparagus",
        "name": "Mary Washington",
        "inventory": 1,
        "seedsInPacket": 70,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "c697ac61-a5c0-434f-96c4-7b8cf637ad1d"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 96,
        "spacingInchesY": 96,
        "daysToHarvest": 100,
        "earliestPlantDate": "05/24",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Pumpkin",
        "name": "Jack O'Lantern",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "aa1e2be2-337a-4675-91db-01a085465404"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 96,
        "spacingInchesY": 96,
        "daysToHarvest": 60,
        "earliestPlantDate": "05/24",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Pumpkin",
        "name": "Fall Rainbow Blend",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "9e5300ca-c798-488a-bc8a-78ae3827286e"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 12,
        "spacingInchesX": 10,
        "spacingInchesY": 10,
        "daysToHarvest": 35,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Flower",
        "subcategory": "Zinnia",
        "name": "California Giants",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "41297216-81ee-411d-9cfd-f9d10c2d8435"
    },
    {
        "minDaysToGerm": 8,
        "maxDaysToGerm": 10,
        "spacingInchesX": 48,
        "spacingInchesY": 72,
        "daysToHarvest": 60,
        "earliestPlantDate": "05/24",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Cucumber",
        "name": "Straight Eight",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "b0b72aac-a599-4518-aa20-1810301aec29"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 12,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 80,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Tomato",
        "name": "Beefsteak",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "ea44c133-220e-4436-88dd-5989754e6376"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 21,
        "spacingInchesX": 1,
        "spacingInchesY": 1,
        "daysToHarvest": 70,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "06/30",
        "category": "Flower",
        "subcategory": "Wildflower",
        "name": "Hummingbird Mix",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "19985d7e-c1b5-4e33-b9de-266ecb40e86f"
    },
    {
        "minDaysToGerm": 14,
        "maxDaysToGerm": 21,
        "spacingInchesX": 6,
        "spacingInchesY": 6,
        "daysToHarvest": 60,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "06/30",
        "category": "Flower",
        "subcategory": "Moonflower",
        "name": "White",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "a044be18-f638-4937-ad67-000dd751289a"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 36,
        "spacingInchesY": 24,
        "daysToHarvest": 80,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Fruit",
        "subcategory": "Tomato",
        "name": "Roma",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "cbf9b8a9-e8b1-42e7-be02-74296ee30019"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 1,
        "spacingInchesY": 1,
        "daysToHarvest": 50,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Spinach",
        "name": "America",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "f062f3b5-e6b2-4bd1-82e9-d380a6cac7cb"
    },
    {
        "minDaysToGerm": 14,
        "maxDaysToGerm": 21,
        "spacingInchesX": 18,
        "spacingInchesY": 18,
        "daysToHarvest": 75,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Flower",
        "subcategory": "Sunflower",
        "name": "Mixed Colors",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Ferry Morse",
        "status": "In Packet",
        "id": "f779224b-2cc2-48a2-a28a-a037a495f9e5"
    },
    {
        "minDaysToGerm": 14,
        "maxDaysToGerm": 21,
        "spacingInchesX": 18,
        "spacingInchesY": 18,
        "daysToHarvest": 80,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Long Red Cayenne Pepper",
        "inventory": 1,
        "seedsInPacket": 30,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "03bb5c3a-3c3a-40d0-a124-c8b18185d0ab"
    },
    {
        "minDaysToGerm": 5,
        "maxDaysToGerm": 10,
        "spacingInchesX": 2,
        "spacingInchesY": 2,
        "daysToHarvest": 80,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/31",
        "category": "Vegetable",
        "subcategory": "Radish",
        "name": "White Icicle",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "d417aa5a-2cf7-47d8-a35f-4b69d311a41f"
    },
    {
        "minDaysToGerm": 14,
        "maxDaysToGerm": 21,
        "spacingInchesX": 12,
        "spacingInchesY": 12,
        "daysToHarvest": 70,
        "earliestPlantDate": "06/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Jalapeno",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "e551e9fd-8b9a-4723-9a24-5afb7c24d872"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 10,
        "spacingInchesX": 8,
        "spacingInchesY": 8,
        "daysToHarvest": 68,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Lettuce",
        "name": "Parris Island Romaine",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "729069cd-5140-4f79-9fce-75bb9378cde0"
    },
    {
        "minDaysToGerm": 3,
        "maxDaysToGerm": 10,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 60,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Cucumber",
        "name": "Marketmore",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "360b1e08-2737-4bc9-850d-c75ee45ab06a"
    },
    {
        "minDaysToGerm": 3,
        "maxDaysToGerm": 10,
        "spacingInchesX": 12,
        "spacingInchesY": 12,
        "daysToHarvest": 50,
        "earliestPlantDate": "04/01",
        "latestPlantDate": "06/30",
        "category": "Vegetable",
        "subcategory": "Cucumber",
        "name": "Double Yield",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "73cae1d5-b1b3-4397-95e6-b2e930cc7c88"
    },
    {
        "minDaysToGerm": 3,
        "maxDaysToGerm": 10,
        "spacingInchesX": 12,
        "spacingInchesY": 12,
        "daysToHarvest": 50,
        "earliestPlantDate": "05/01",
        "latestPlantDate": "07/31",
        "category": "Herb",
        "subcategory": "Cilantro",
        "name": "Slow Bolt",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "78102080-0f47-408f-8ee8-d3c32b501a34"
    },
    {
        "minDaysToGerm": 7,
        "maxDaysToGerm": 14,
        "spacingInchesX": 18,
        "spacingInchesY": 18,
        "daysToHarvest": 70,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Sweet Banana",
        "inventory": 1,
        "seedsInPacket": 28,
        "brand": "Seeds of Change",
        "status": "In Packet",
        "id": "93410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
    {
        "minDaysToGerm": 30,
        "maxDaysToGerm": 40,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 150,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Superhot Pepper",
        "name": "Ghost (Bhut Jolokia)",
        "inventory": 1,
        "seedsInPacket": 10,
        "brand": "Pepper Joe's",
        "status": "In Packet",
        "id": "94410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
    {
        "minDaysToGerm": 30,
        "maxDaysToGerm": 40,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 150,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Pepper",
        "name": "Kristian Thai",
        "inventory": 1,
        "seedsInPacket": 10,
        "brand": "Pepper Joe's",
        "status": "In Packet",
        "id": "04410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
    {
        "minDaysToGerm": 30,
        "maxDaysToGerm": 40,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 150,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Superhot Pepper",
        "name": "Carolina Reaper",
        "inventory": 1,
        "seedsInPacket": 10,
        "brand": "Pepper Joe's",
        "status": "In Packet",
        "id": "44410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
    {
        "minDaysToGerm": 30,
        "maxDaysToGerm": 40,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 150,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Superhot Pepper",
        "name": "Ghost (Wicked F1)",
        "inventory": 1,
        "seedsInPacket": 10,
        "brand": "Pepper Joe's",
        "status": "In Packet",
        "id": "4e410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
    {
        "minDaysToGerm": 30,
        "maxDaysToGerm": 40,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 150,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Superhot Pepper",
        "name": "Dragon's Breath",
        "inventory": 1,
        "seedsInPacket": 10,
        "brand": "Pepper Joe's",
        "status": "In Packet",
        "id": "42410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
    {
        "minDaysToGerm": 30,
        "maxDaysToGerm": 40,
        "spacingInchesX": 24,
        "spacingInchesY": 24,
        "daysToHarvest": 150,
        "earliestPlantDate": "03/01",
        "latestPlantDate": "05/01",
        "category": "Vegetable",
        "subcategory": "Superhot Pepper",
        "name": "Genghis Khan Brain",
        "inventory": 1,
        "seedsInPacket": 10,
        "brand": "Pepper Joe's",
        "status": "In Packet",
        "id": "e2410a44-86ea-4693-b3dc-edce8aa73a9e"
    },
]